[project]
name = "spectral-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "lightgbm>=4.6.0",
    "mlflow>=3.10.1",
    "nbdime>=4.0.4",
    "nbstripout>=0.9.1",
    "numpy>=2.4.2",
    "pandas>=2.3.3",
    "plotly>=6.6.0",
    "polars>=1.38.1",
    "pywavelets>=1.9.0",
    "scikit-learn>=1.8.0",
    "signate>=0.10.4",
    "tabpfn>=6.4.1",
]

[project.scripts]
spectral-analysis = "src.cli:main"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "black>=26.1.0",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "ruff>=0.15.5",
]
